apiVersion: apps/v1
kind: Deployment
metadata:
  name: home_enviorment_monitor
  labels:
    app: home_enviorment_monitor 
spec:
  replicas: 8
  selector:
    matchLabels:
      app: home_enviorment_monitor 
  template:
    metadata:
      labels:
        app: home_enviorment_monitor
    spec:
      containers:
      - name: home_enviorment_monitor
        image: frixxie/home_enviorment_monitor:pi_latest
        imagePullPolicy: Always
        ports:
        - containerPort: 65534
