apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-enviorment-monitor
  labels:
    app: home-enviorment-monitor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: home-enviorment-monitor
  template:
    metadata:
      labels:
        app: home-enviorment-monitor
    spec:
      containers:
      - name: home-enviorment-monitor
        image: frixxie/home_enviorment_monitor:pi_latest
        imagePullPolicy: Always
        ports:
        - containerPort: 65534
